# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Reka yoga
tagline:          'A Jekyll theme'
description:      'Este es el sitio web de <a href="https://www.instagram.com/rekayoga.centrointegral/" target="_blank">Reka Yoga</a>. Made by Pablo.'
url:              https://www.instagram.com/rekayoga.centrointegral
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
